/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WardenDashboardRouteImport } from './routes/warden-dashboard'
import { Route as StudentsRouteImport } from './routes/students'
import { Route as StudentDashboardRouteImport } from './routes/student-dashboard'
import { Route as RoomsRouteImport } from './routes/rooms'
import { Route as NoticesRouteImport } from './routes/notices'
import { Route as FeesRouteImport } from './routes/fees'
import { Route as ComplaintsRouteImport } from './routes/complaints'
import { Route as AdminDashboardRouteImport } from './routes/admin-dashboard'
import { Route as IndexRouteImport } from './routes/index'

const WardenDashboardRoute = WardenDashboardRouteImport.update({
  id: '/warden-dashboard',
  path: '/warden-dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentsRoute = StudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentDashboardRoute = StudentDashboardRouteImport.update({
  id: '/student-dashboard',
  path: '/student-dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const RoomsRoute = RoomsRouteImport.update({
  id: '/rooms',
  path: '/rooms',
  getParentRoute: () => rootRouteImport,
} as any)
const NoticesRoute = NoticesRouteImport.update({
  id: '/notices',
  path: '/notices',
  getParentRoute: () => rootRouteImport,
} as any)
const FeesRoute = FeesRouteImport.update({
  id: '/fees',
  path: '/fees',
  getParentRoute: () => rootRouteImport,
} as any)
const ComplaintsRoute = ComplaintsRouteImport.update({
  id: '/complaints',
  path: '/complaints',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/admin-dashboard',
  path: '/admin-dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin-dashboard': typeof AdminDashboardRoute
  '/complaints': typeof ComplaintsRoute
  '/fees': typeof FeesRoute
  '/notices': typeof NoticesRoute
  '/rooms': typeof RoomsRoute
  '/student-dashboard': typeof StudentDashboardRoute
  '/students': typeof StudentsRoute
  '/warden-dashboard': typeof WardenDashboardRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin-dashboard': typeof AdminDashboardRoute
  '/complaints': typeof ComplaintsRoute
  '/fees': typeof FeesRoute
  '/notices': typeof NoticesRoute
  '/rooms': typeof RoomsRoute
  '/student-dashboard': typeof StudentDashboardRoute
  '/students': typeof StudentsRoute
  '/warden-dashboard': typeof WardenDashboardRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin-dashboard': typeof AdminDashboardRoute
  '/complaints': typeof ComplaintsRoute
  '/fees': typeof FeesRoute
  '/notices': typeof NoticesRoute
  '/rooms': typeof RoomsRoute
  '/student-dashboard': typeof StudentDashboardRoute
  '/students': typeof StudentsRoute
  '/warden-dashboard': typeof WardenDashboardRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin-dashboard'
    | '/complaints'
    | '/fees'
    | '/notices'
    | '/rooms'
    | '/student-dashboard'
    | '/students'
    | '/warden-dashboard'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin-dashboard'
    | '/complaints'
    | '/fees'
    | '/notices'
    | '/rooms'
    | '/student-dashboard'
    | '/students'
    | '/warden-dashboard'
  id:
    | '__root__'
    | '/'
    | '/admin-dashboard'
    | '/complaints'
    | '/fees'
    | '/notices'
    | '/rooms'
    | '/student-dashboard'
    | '/students'
    | '/warden-dashboard'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  ComplaintsRoute: typeof ComplaintsRoute
  FeesRoute: typeof FeesRoute
  NoticesRoute: typeof NoticesRoute
  RoomsRoute: typeof RoomsRoute
  StudentDashboardRoute: typeof StudentDashboardRoute
  StudentsRoute: typeof StudentsRoute
  WardenDashboardRoute: typeof WardenDashboardRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/warden-dashboard': {
      id: '/warden-dashboard'
      path: '/warden-dashboard'
      fullPath: '/warden-dashboard'
      preLoaderRoute: typeof WardenDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/students': {
      id: '/students'
      path: '/students'
      fullPath: '/students'
      preLoaderRoute: typeof StudentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student-dashboard': {
      id: '/student-dashboard'
      path: '/student-dashboard'
      fullPath: '/student-dashboard'
      preLoaderRoute: typeof StudentDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rooms': {
      id: '/rooms'
      path: '/rooms'
      fullPath: '/rooms'
      preLoaderRoute: typeof RoomsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notices': {
      id: '/notices'
      path: '/notices'
      fullPath: '/notices'
      preLoaderRoute: typeof NoticesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fees': {
      id: '/fees'
      path: '/fees'
      fullPath: '/fees'
      preLoaderRoute: typeof FeesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/complaints': {
      id: '/complaints'
      path: '/complaints'
      fullPath: '/complaints'
      preLoaderRoute: typeof ComplaintsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-dashboard': {
      id: '/admin-dashboard'
      path: '/admin-dashboard'
      fullPath: '/admin-dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  ComplaintsRoute: ComplaintsRoute,
  FeesRoute: FeesRoute,
  NoticesRoute: NoticesRoute,
  RoomsRoute: RoomsRoute,
  StudentDashboardRoute: StudentDashboardRoute,
  StudentsRoute: StudentsRoute,
  WardenDashboardRoute: WardenDashboardRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
